In [20]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# Layers without Parameters

In [21]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [22]:
layer = CenteredLayer()
layer(torch.tensor([1.0, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [23]:
net = nn.Sequential(nn.LazyLinear(128), CenteredLayer())

In [24]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(4.6566e-09, grad_fn=<MeanBackward0>)

# Layers with Parameters

In [25]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [26]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[-1.5858, -1.6585,  0.3149],
        [-0.6357,  0.7882,  0.2131],
        [ 0.6027,  0.8302,  0.0313],
        [ 0.5878, -1.4355,  1.2464],
        [-0.0330, -0.5100, -1.5911]], requires_grad=True)

In [27]:
linear(torch.rand(2, 5))

tensor([[0.0000, 0.3176, 0.0000],
        [0.0000, 0.0000, 1.0821]])

In [28]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[3.9196],
        [5.2593]])