In [25]:
import torch
import torch.nn as nn
import aditmaz95

In [26]:
aditmaz95.cpu(),aditmaz95.gpu()

(device(type='cpu'), device(type='cuda', index=0))

In [27]:
aditmaz95.num_gpus()

1

In [28]:
aditmaz95.try_gpu(),aditmaz95.try_all_gpus()

(device(type='cuda', index=0), [device(type='cuda', index=0)])

# Tensors and GPUs

In [29]:
x = torch.tensor([1, 2, 3])
x.device

device(type='cpu')

In [30]:
X = torch.ones(2, 3, device=aditmaz95.try_gpu())
X

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [31]:
Y = torch.rand(2, 3, device=aditmaz95.try_gpu())
Y

tensor([[0.4139, 0.4703, 0.4711],
        [0.3311, 0.9606, 0.7549]], device='cuda:0')

# Neural Networks and GPUs

In [32]:
net = nn.Sequential(nn.LazyLinear(1))
net = net.to(device=aditmaz95.try_gpu())

In [33]:
net(X)

tensor([[-1.1489],
        [-1.1489]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [34]:
net[0].weight.data.device

device(type='cuda', index=0)